### ISSUE TITLE
Broken with queue-async@1.1.0

### ISSUE THREAD

**Issue by rclark** [mapbox/s3scan#10]
The get stream is broken on queue-async@1.1.0.

```
/Users/r/gh/mapbox/s3scan/node_modules/aws-sdk/lib/request.js:30
            throw err;
                  ^
Error
    at check (/Users/r/gh/mapbox/s3scan/node_modules/queue-async/build/queue.js:56:36)
    at Object.q.defer (/Users/r/gh/mapbox/s3scan/node_modules/queue-async/build/queue.js:67:9)
    at Transform.getStream._transform (/Users/r/gh/mapbox/s3scan/lib/get.js:32:21)
```

**Comment by rclark** [comment]
https://github.com/mbostock/queue/issues/41

Pinning to 1.0.7 in the meantime: 24f0a377a90a26a2395e3a8b04f37f10f107912d
